default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: newsroom-april_development

test: &test
  <<: *default
  database: newsroom-april_test

production:
  <<: *default
  database: newsroom-april_production
  username: newsroom-april
  password: <%= ENV['NEWSROOM-APRIL_DATABASE_PASSWORD'] %>

cucumber:
  <<: *test
